const sidebars = {
  tutorialSidebar: [
    'About',
    'etl/etl-features',
    {
      type: 'category',
      label: 'AI Search',
      items: [
        'search/search-overview',
        'search/search-elastic',
        {
          type: 'category',
          label: 'Slack',
          items: ['search/search-slack', 'search/search-slack-app'],
        },
        'search/search-chatterbox',
        'search/search-prompt-flows',
        'search/search-loading-flows',
      ],
    },
    {
      type: 'category',
      label: 'AI Models',
      items: ['models/models-overview'],
    },
    // USER GUIDE
    {
      type: 'category',
      label: 'User Guide',
      items: [
        // {
        //   type: 'category',
        //   label: 'Flow design considerations',
        //   items: [
        //     'user-guide/considerations/considerations-intro',
        //     'user-guide/considerations/how-flows-work',
        //     'user-guide/considerations/dev-prod-modes',
        //     'user-guide/considerations/batching',
        //     'user-guide/considerations/debugging',
        //     'user-guide/considerations/javascript',
        //     'user-guide/considerations/edge-validation-transformation-mapping',
        //     'user-guide/considerations/datastore',
        //     'user-guide/considerations/flow-termination',
        //     'user-guide/considerations/test-data',
        //     'user-guide/considerations/error-handling',
        //     'user-guide/considerations/subflows',
        //     'user-guide/considerations/queueing',
        //     'user-guide/considerations/mqtt',
        //     'user-guide/considerations/performance-tuning',
        //     'user-guide/considerations/documenting',
        //     'user-guide/considerations/performance-tuning',
        //   ],
        // },
        'user-guide/considerations/considerations-intro',
        {
          type: 'category',
          label: 'Editor',
          items: [
            'user-guide/editor/Editor',
            'user-guide/editor/Flow-Editor-Layout',
            'user-guide/editor/Flow-settings',
            'user-guide/editor/Recent-Flows',
            'user-guide/editor/Flows-listing',
            'user-guide/editor/Commander',
            'user-guide/editor/Moving-edges',
            'user-guide/editor/Selecting-multiple-blocks',
            'user-guide/editor/Block-navigation',
            'user-guide/editor/Flow-documentation',
            'user-guide/editor/Execution-history',
            'user-guide/editor/Debugging',
            'user-guide/editor/edge-inspection',
            'user-guide/editor/Named-Saves',
            'user-guide/editor/Clone',
          ],
        },
        {
          type: 'category',
          label: 'Blocks',
          items: [
            {
              type: 'category',
              label: 'Core',
              items: [
                'user-guide/block-types/core/Receiver',
                'user-guide/block-types/core/Terminator',
                'user-guide/block-types/core/sinkhole',
                'user-guide/block-types/core/Javascript',
                'user-guide/block-types/core/Iterator',
                'user-guide/block-types/core/joiner',
                'user-guide/block-types/core/Key-Filter',
                'user-guide/block-types/core/Has-Data',
                'user-guide/block-types/core/Splitter',
                'user-guide/block-types/core/Merger',
                'user-guide/block-types/core/Collector',
                'user-guide/block-types/core/Branch',
                'user-guide/block-types/core/Branch-To-Subflow',
                'user-guide/block-types/core/Subflow',
                'user-guide/block-types/core/Batch-End',
                'user-guide/block-types/core/test-data',
                'user-guide/block-types/core/Variable-Set-Get',
                'user-guide/block-types/core/Console-Message',
                'user-guide/block-types/core/Annotation',
                'user-guide/block-types/core/commander-block',
              ],
            },
            {
              type: 'category',
              label: 'AI',
              items: [
                'user-guide/block-types/ai/ai-search-prompt',
                'user-guide/block-types/ai/ai-qdrant',
              ],
            },
            {
              type: 'category',
              label: 'Utility',
              items: [
                'user-guide/block-types/utility/Data-Store',
                'user-guide/block-types/utility/MemStore',
                'user-guide/block-types/utility/file-reader-writer',
                'user-guide/block-types/utility/SQL',
                'user-guide/block-types/utility/REST-Call',
                'user-guide/block-types/utility/Mapper',
                'user-guide/block-types/utility/airtable',
                'user-guide/block-types/utility/audit',
              ],
            },
            {
              type: 'category',
              label: 'SQL',
              items: [
                'user-guide/block-types/utility/sql/sql-configuration',
                'user-guide/block-types/utility/sql/sql-mapping',
                'user-guide/block-types/utility/sql/sql-edge',
                'user-guide/block-types/utility/sql/sql-select',
                'user-guide/block-types/utility/sql/sql-insert',
                'user-guide/block-types/utility/sql/sql-update',
                'user-guide/block-types/utility/sql/sql-upsert',
                'user-guide/block-types/utility/sql/sql-delete',
                'user-guide/block-types/utility/sql/sql-raw',
                'user-guide/block-types/utility/sql/sql-editing',
              ],
            },
            {
              type: 'category',
              label: 'Elastic Search',
              items: [
                'user-guide/block-types/elastic/elastic-ingest',
                'user-guide/block-types/elastic/elastic-search',
              ],
            },
            {
              type: 'category',
              label: 'Slack',
              items: ['user-guide/block-types/slack/slack-formatter'],
            },
            {
              type: 'category',
              label: 'HubSpot',
              items: [
                'user-guide/block-types/hubspot/hs-read',
                'user-guide/block-types/hubspot/hs-write',
                'user-guide/block-types/hubspot/hs-get-associated',
                'user-guide/block-types/hubspot/hs-create-associations',
                'user-guide/block-types/hubspot/hs-get-all-owners',
                'user-guide/block-types/hubspot/hs-owner-translate',
                'user-guide/block-types/hubspot/hs-merge',
                'user-guide/block-types/hubspot/hs-timeline-write',
                'user-guide/block-types/hubspot/hs-search',
                'user-guide/block-types/hubspot/hs-options',
              ],
            },
            {
              type: 'category',
              label: 'Salesforce',
              items: [
                'user-guide/block-types/salesforce/sf-read-object',
                'user-guide/block-types/salesforce/sf-write-object',
                'user-guide/block-types/salesforce/SalesForce-Get-Associated-Object',
                'user-guide/block-types/salesforce/SalesForce-Set-Assciations',
                'user-guide/block-types/salesforce/SalesForce-Owner-Translate',
              ],
            },
            {
              type: 'category',
              label: 'Store Helpers',
              items: ['user-guide/block-types/store-helpers/timestamper'],
            },
          ],
        },
        {
          type: 'category',
          label: 'Custom Blocks & Plugins',
          items: [
            'user-guide/plugin/overview',
            'user-guide/plugin/sdk',
            'user-guide/plugin/cli',
            'user-guide/plugin/create',
            'user-guide/plugin/config',
            'user-guide/plugin/definition',
            'user-guide/plugin/client',
            'user-guide/plugin/server',
            'user-guide/plugin/batcher',
          ],
        },
        'user-guide/History-data-storage-levels',
        'user-guide/Monitoring',
        'user-guide/Structures-and-mapping',
        'user-guide/Launching-flows',
        'user-guide/Connections',
        'user-guide/Secrets',
        'user-guide/Batching',
        'user-guide/Queuing',
        'user-guide/Scheduled-Flows',
        'user-guide/Dev-Prod-Modes',
        'user-guide/Memory-Store',
        'user-guide/Data-Store-section',
        'user-guide/Auditing',
        'user-guide/Error-Handling',
        'user-guide/Data-and-Memory-Store-Browser',
        'user-guide/MQTT',
        'user-guide/Tags',
        'user-guide/Tests',
        'user-guide/Alerts',
        'user-guide/Logging',
        'user-guide/Global-Settings',
        'user-guide/Transferring-Data',
        'user-guide/Troubleshooting',
        'user-guide/Security',
        'user-guide/Performance-Tuning',
        'user-guide/Deployment',
      ],
    },
  ],
};

module.exports = sidebars;
